ui:
  ui_wh: [1600, 900]
  logger_wh: [200, 100]
  max_log_num: 500
  color_video_wh: [640, 480]
  status_list_wh: [200, 100]
  result_logger_wh: [200, 100]
  button_wh: [100, 50]

layout:
  logger_rc: [1, 1]
  color_video_rc: [0, 0]
  status_list_rc: [1, 0]
  result_logger_rc: [0, 1]

topic:
  color_img_raw: "/camera/color/image_raw"
  depth_img_raw: "/camera/depth/image_raw"
  log_text: "log_text"
  result_text : "result_text"
  processed_image: "processed_image"

log:
  log_rate: 1

log_level:
  debug: 0
  info: 1
  warning: 2
  error: 3

model:
  input_num: 3
  input_hw: [640, 480]
